### ISSUE TITLE
Null pointer exception in at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VisioPositionUtil.getPositionInterpolatedInTime

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/agentpolis#80]
(VisManager.java:315) - Vis layer cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.ManageableLayer@7a010621 has thrown the following exception:
java.lang.NullPointerException
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VisioPositionUtil.getPositionInterpolatedInTime(VisioPositionUtil.java:208)
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VisioPositionUtil.getCanvasPositionInterpolatedInTime(VisioPositionUtil.java:227)
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VisioPositionUtil.getCanvasPositionInterpolatedInTime(VisioPositionUtil.java:196)
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VisioPositionUtil.getCanvasPositionInterpolatedInTime(VisioPositionUtil.java:239)
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.VehicleLayer.getEntityPositionInTime(VehicleLayer.java:65)
	at cz.cvut.fel.aic.agentpolis.simulator.visualization.visio.EntityLayer.paint(EntityLayer.java:104)
	at cz.cvut.fel.aic.alite.vis.layer.GroupLayer.paint(GroupLayer.java:73)
	at cz.cvut.fel.aic.alite.vis.layer.toggle.ToggleLayer.paint(ToggleLayer.java:51)
	at cz.cvut.fel.aic.alite.vis.VisManager.drawLayer(VisManager.java:308)
	at cz.cvut.fel.aic.alite.vis.VisManager.update(VisManager.java:301)
	at cz.cvut.fel.aic.alite.vis.VisManager.access$000(VisManager.java:69)
	at cz.cvut.fel.aic.alite.vis.VisManager$1.run(VisManager.java:96)
	at java.lang.Thread.run(Thread.java:748)

**Comment by F-I-D-O** [comment]
Just run the simulation, and wait for it :)
